const path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require(path.join(require('node:os').tmpdir(),'utt-monthly-report-qa/node_modules/playwright'));
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{const context=await browser.newContext();const blocked=[],errors=[];await context.route('**/*',r=>{if(r.request().url().startsWith('http://localhost:3000/')||r.request().url().startsWith('data:'))return r.continue();blocked.push(r.request().url());return r.abort();});const p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto('http://localhost:3000/tests/browser/school-hub.html');
for(const [name,width,height] of [['1366',1366,768],['1920',1920,1080],['mobile',390,844]]){
 await p.setViewportSize({width,height});const hub=p.getByRole('dialog',{name:'รายละเอียดโรงเรียน',exact:true});await hub.waitFor();const history=p.getByRole('region',{name:'ประวัติการดำเนินงาน'});await history.scrollIntoViewIfNeeded();assert.equal(await history.getByRole('button').count(),3);assert(!(await hub.innerText()).includes('import_school_qa'));await p.screenshot({path:`docs/qa-school-hub/${name}.png`});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 for(const [text,dialog,signature,key] of [['ยื่นหนังสือ','รายละเอียดการยื่นหนังสือ','HUB-LETTER-001','Enter'],['นัดหมายแนะแนว','รายละเอียดนัดหมาย','APPOINTMENT-SOURCE-NOTE','Space'],['ออกแนะแนว ·','รายละเอียดการออกแนะแนว','GUIDANCE-SOURCE-NOTE','Enter']]){
  const row=history.getByRole('button').filter({hasText:text});await row.focus();await row.press(key);const detail=p.getByRole('dialog',{name:dialog,exact:true});await detail.waitFor();assert((await detail.innerText()).includes(signature));if(dialog==='รายละเอียดนัดหมาย')assert(!(await detail.innerText()).includes('13:00 - 12:00'));
  const close=dialog==='รายละเอียดนัดหมาย'?detail.getByRole('button',{name:'ปิดรายละเอียดนัดหมาย'}):detail.getByRole('button',{name:'ปิดรายละเอียด',exact:true});await close.click();await detail.waitFor({state:'detached'});assert(await row.evaluate(e=>e===document.activeElement));
 }
}
await p.getByLabel('รอบทดสอบ').selectOption('next');await p.getByRole('region',{name:'ประวัติการดำเนินงาน'}).scrollIntoViewIfNeeded();assert.equal(await p.getByRole('region',{name:'ประวัติการดำเนินงาน'}).getByRole('button').count(),4);assert((await p.locator('p[role=status]').innerText()).includes('รอนัดหมาย'));await p.getByLabel('รอบทดสอบ').selectOption('active');await p.getByRole('button',{name:'ดูนัดหมายที่มีอยู่'}).click();await p.getByRole('dialog',{name:'รายละเอียดนัดหมาย',exact:true}).waitFor();await p.getByRole('button',{name:'ปิดรายละเอียดนัดหมาย'}).click();
await p.getByRole('button',{name:'สลับรายงาน'}).click();await p.getByLabel('ปี พ.ศ.',{exact:true}).selectOption('2026');await p.getByLabel('เดือน',{exact:true}).selectOption('9');
for(const [label,dialog,signature] of [['ยื่นหนังสือ','รายละเอียดการยื่นหนังสือ','HUB-LETTER-001'],['ออกแนะแนว','รายละเอียดการออกแนะแนว','GUIDANCE-SOURCE-NOTE']]){await p.locator('.monthly-card').filter({hasText:label}).click();const d=p.getByRole('dialog',{name:dialog,exact:true});await d.waitFor();assert((await d.innerText()).includes(signature));await d.getByRole('button',{name:'ปิดรายละเอียด',exact:true}).click();}
assert.deepEqual(errors,[]);console.log(JSON.stringify({passed:['1366','1920','mobile','timeline','history','keyboard source navigation','close focus','new cycle','existing appointment action','monthly report source parity'],externalRequestsBlocked:blocked.length,pageErrors:errors}));}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
