import {describe,it,expect} from 'vitest';
import {getSchoolActivityHistory,submissionPeople} from '../src/utils/schoolActivityHistory';
import {getSchoolWorkflow,getSchoolEffectiveStatus,formatSchoolDisplayName,getCleanSchoolCode} from '../src/utils/schoolStatus';
import {buildMonthlyReportRows} from '../src/utils/monthlyReport';
import {formatAppointmentTime} from '../src/utils/appointmentUtils';
import type {School,DocumentSubmission,Appointment,FieldTrip} from '../src/types';
const a={id:'school-a',schoolId:'1064620210',schoolName:'โรงเรียนทดสอบ',teamId:'team1',currentStatus:'NOT_STARTED'} as School;
const b={...a,id:'school-b',schoolId:'1064620211'};
const s={id:'s',schoolId:a.id,schoolName:a.schoolName,submissionDate:'2026-09-01',submittedByNames:['ครูหนึ่ง','ครูสอง'],teamId:'team1',status:'WAITING_APPOINTMENT'} as DocumentSubmission;
const p={id:'p',schoolId:a.id,schoolName:a.schoolName,submissionId:'s',date:'2026-09-15',startTime:'13:00',endTime:'12:00',counselorName:'ครูหนึ่ง',status:'CONFIRMED'} as Appointment;
const t={id:'t',appointmentId:'p',date:'2026-09-22',schools:[{schoolId:a.id,schoolName:a.schoolName}],counselorName:'ครูหนึ่ง',teamId:'team1',workType:'แนะแนว'} as FieldTrip;
const workflow=(subs=[s],appts=[p],trips=[t])=>getSchoolWorkflow(a,subs,appts,trips,[a,b]);
const history=(subs=[s],appts=[p],trips=[t])=>getSchoolActivityHistory(a,[a,b],subs,appts,trips);
describe('school workflow hub',()=>{
 it('A/C completed appointment without FieldTrip leaves step4 empty',()=>{const w=workflow([s],[{...p,status:'COMPLETED',note:'แนะแนวแล้ว'}],[]);expect(w.schoolSubmissions).toHaveLength(1);expect(w.schoolAppointments).toHaveLength(1);expect(w.schoolTrips).toHaveLength(0);expect(w.status).toBe('APPOINTED');});
 it('B actual FieldTrip supplies the guidance source without replacing the appointment',()=>{const w=workflow();expect(w.schoolSubmissions[0]).toBe(s);expect(w.schoolAppointments[0]).toBe(p);expect(w.schoolTrips[0]).toBe(t);});
 it('G completed appointments cannot create a monthly work row',()=>{const w=workflow([s],[{...p,status:'COMPLETED'}],[]);const rows=buildMonthlyReportRows(w.schoolSubmissions,w.schoolTrips,[a,b]).rows;expect(rows.map(r=>r.sourceType)).toEqual(['SUBMISSION']);});
 it('1 no submissions has not started',()=>expect(workflow([],[],[]).status).toBe('NOT_STARTED'));
 it('2 submission completes letter step',()=>expect(workflow([s],[],[]).current.submissions).toEqual([s]));
 it('3 linked appointment completes appointment step',()=>expect(workflow([s],[p],[]).status).toBe('APPOINTED'));
 it('4 fieldtrip completes guidance',()=>expect(workflow().status).toBe('GUIDANCE_COMPLETED'));
 it('5 submission target is actual source ID',()=>expect(history().find(i=>i.sourceType==='SUBMISSION')?.sourceId).toBe(s.id));
 it('6 appointment target is actual source ID',()=>expect(history().find(i=>i.sourceType==='APPOINTMENT')?.sourceId).toBe(p.id));
 it('7 guidance target is actual source ID',()=>expect(history().find(i=>i.sourceType==='GUIDANCE')?.sourceId).toBe(t.id));
 it('8 preserves multiple letters',()=>expect(history([s,{...s,id:'s2'}]).filter(i=>i.sourceType==='SUBMISSION')).toHaveLength(2));
 it('9 preserves multiple appointments',()=>expect(history([s],[p,{...p,id:'p2'}]).filter(i=>i.sourceType==='APPOINTMENT')).toHaveLength(2));
 it('10 preserves multiple trips',()=>expect(history([s],[p],[t,{...t,id:'t2'}]).filter(i=>i.sourceType==='GUIDANCE')).toHaveLength(2));
 it('11 sorts newest first',()=>expect(history().map(i=>i.sourceId)).toEqual(['t','p','s']));
 it('12 identical names never cross-link',()=>expect(history([{...s,schoolId:b.id}],[],[])).toEqual([]));
 it('13 hides technical school codes',()=>expect(getCleanSchoolCode('import_school_123')).toBeNull());
 it('14 strips display prefix only',()=>{expect(formatSchoolDisplayName(a.schoolName)).toBe('ทดสอบ');expect(a.schoolName).toBe('โรงเรียนทดสอบ');});
 it('15 displays all stored submitters',()=>expect(submissionPeople(s).map(p=>p.name)).toEqual(['ครูหนึ่ง','ครูสอง']));
 it('16 historical vehicle missing stays missing',()=>expect(history().every(i=>i.vehicleName==='')).toBe(true));
 it('17 invalid end time not displayed',()=>{expect(formatAppointmentTime(p.startTime,p.endTime)).toContain('13:00');expect(formatAppointmentTime(p.startTime,p.endTime)).not.toContain('12:00');});
 it('18 multi-school trip uses one source ID',()=>{const multi={...t,schools:[...t.schools,{schoolId:b.id,schoolName:b.schoolName}]};expect(getSchoolActivityHistory(b,[a,b],[s],[p],[multi])[0].sourceId).toBe(t.id);expect(history([s],[p],[multi])[0].sourceId).toBe(t.id);});
 it('19 report and history share exact source IDs',()=>{const rows=buildMonthlyReportRows([s],[t],[a,b]).rows;expect(rows.every(r=>history().some(h=>h.sourceType===r.sourceType&&h.sourceId===r.sourceId))).toBe(true);});
 it('20 new cycle does not erase old history or inherit completion',()=>{const next={...s,id:'next',submissionDate:'2027-09-01'};expect(workflow([s,next]).status).toBe('WAITING_APPOINTMENT');expect(history([s,next])).toHaveLength(4);});
 it('dashboard shares current cycle status',()=>expect(getSchoolEffectiveStatus(a,[s],[p],[t],[a,b])).toBe(workflow().status));
 it('legacy completion retains appointment provenance',()=>{const items=history([s],[{...p,status:'COMPLETED'}],[]);expect(items.some(i=>i.sourceType==='GUIDANCE')).toBe(false);expect(items[0].sourceId).toBe(p.id);});
 it('same date is not an invented cycle',()=>expect(workflow([s],[{...p,submissionId:undefined}],[]).current.submissions).toEqual([]));
 it('resolves unique legacy code consistently',()=>expect(history([{...s,schoolId:a.schoolId}],[],[])[0].sourceId).toBe(s.id));
 it('recorder ID is not used as submitter identity',()=>expect(submissionPeople({...s,submittedById:'admin'}).some(p=>p.id==='admin')).toBe(false));
});
